//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaderPush.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopLink
    {
        public int Id { get; set; }
        public string Shop { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> UninstallDate { get; set; }
        public Nullable<bool> IsPremium { get; set; }
        public Nullable<int> SendLimit { get; set; }
        public Nullable<long> PremiumID { get; set; }
    }
}
